package model.pojo;
// Generated Nov 12, 2014 10:39:01 PM by Hibernate Tools 4.3.1


import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cinema generated by hbm2java
 */
@Entity
@Table(name="Cinema"
    ,schema="dbo"
    ,catalog="Alpha"
)
public class Cinema  implements java.io.Serializable {


     private int cinema;
     private int seatmax;
     private List<Movie> movielist = null;
     
    public Cinema() {
    }

    public Cinema(int seatmax) {
       this.seatmax = seatmax;
    }
    
    public List<Movie> addMovieList(List<Movie> movielist) {
        return this.movielist = movielist;
    }

    public List<Movie> getMovieList() {
        return this.movielist;
    }
   
     @Id 

    
    @Column(name="cinema", nullable=false)
    public int getCinema() {
        return this.cinema;
    }
    
    public void setCinema(int cinema) {
        this.cinema = cinema;
    }

    
    @Column(name="seatmax", nullable=false)
    public int getSeatmax() {
        return this.seatmax;
    }
    
    public void setSeatmax(int seatmax) {
        this.seatmax = seatmax;
    }

}


