package model.pojo;
// Generated Nov 15, 2014 4:01:32 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Code generated by hbm2java
 */
@Entity
@Table(name = "Code"
    ,schema = "dbo"
    ,catalog = "Alpha"
)
public class Code implements java.io.Serializable {

    private String code;
    private String time;
    private int cinema;
    private String mname;
    private String seatname;

    public Code() {
    }

    public Code(String code, String time, int cinema, String mname, String seatname) {
        this.code = code;
        this.time = time;
        this.cinema = cinema;
        this.mname = mname;
        this.seatname = seatname;
    }

    @Id

    @Column(name = "code", nullable = false, length = 100)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "time", nullable = false, length = 5)
    public String getTime() {
        return this.time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    @Column(name = "cinema", nullable = false)
    public int getCinema() {
        return this.cinema;
    }

    public void setCinema(int cinema) {
        this.cinema = cinema;
    }

    @Column(name = "mname", nullable = false, length = 50)
    public String getMname() {
        return this.mname;
    }

    public void setMname(String mname) {
        this.mname = mname;
    }

    @Column(name = "seatname", nullable = false, length = 15)
    public String getSeatname() {
        return this.seatname;
    }

    public void setSeatname(String seatname) {
        this.seatname = seatname;
    }

}
