package model.pojo;
// Generated Oct 26, 2014 4:31:14 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movie generated by hbm2java
 */
@Entity
@Table(name = "Movie", schema = "dbo", catalog = "Alpha"
)
public class Movie implements java.io.Serializable {

    private String mname;
    private Date releasedate;
    private String type;
    private Date duration;
    private String synopsis;
    private byte[] mimg;

    public Movie() {
    }

    public Movie(String mname, Date releasedate, String type, Date duration, String synopsis, byte[] mimg) {
        this.mname = mname;
        this.releasedate = releasedate;
        this.type = type;
        this.duration = duration;
        this.synopsis = synopsis;
        this.mimg = mimg;
    }

    @Id

    @Column(name = "mname", unique = true, nullable = false, length = 50)
    public String getMname() {
        return this.mname;
    }

    public void setMname(String mname) {
        this.mname = mname;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "releasedate", nullable = false, length = 10)
    public Date getReleasedate() {
        return this.releasedate;
    }

    public void setReleasedate(Date releasedate) {
        this.releasedate = releasedate;
    }

    @Column(name = "type", nullable = false, length = 50)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "duration", nullable = false, length = 16)
    public Date getDuration() {
        return this.duration;
    }

    public void setDuration(Date duration) {
        this.duration = duration;
    }

    @Column(name = "synopsis", nullable = false, length = 500)
    public String getSynopsis() {
        return this.synopsis;
    }

    public void setSynopsis(String synopsis) {
        this.synopsis = synopsis;
    }

    @Column(name = "mimg", nullable = false)
    public byte[] getMimg() {
        return this.mimg;
    }

    public void setMimg(byte[] mimg) {
        this.mimg = mimg;
    }

}
