package model.pojo;
// Generated Nov 15, 2014 4:01:32 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Seat generated by hbm2java
 */
@Entity
@Table(name="Seat"
    ,schema="dbo"
    ,catalog="Alpha"
)
public class Seat  implements java.io.Serializable {


     private SeatId id;
     private int type;
     private boolean avalible;

    public Seat() {
    }

    public Seat(SeatId id, int type, boolean avalible) {
       this.id = id;
       this.type = type;
       this.avalible = avalible;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="time", column=@Column(name="time", nullable=false, length=5) ), 
        @AttributeOverride(name="cinema", column=@Column(name="cinema", nullable=false) ), 
        @AttributeOverride(name="seat", column=@Column(name="seat", nullable=false, length=3) ) } )
    public SeatId getId() {
        return this.id;
    }
    
    public void setId(SeatId id) {
        this.id = id;
    }

    
    @Column(name="type", nullable=false)
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }

    
    @Column(name="avalible", nullable=false)
    public boolean isAvalible() {
        return this.avalible;
    }
    
    public void setAvalible(boolean avalible) {
        this.avalible = avalible;
    }
}


