package model.pojo;
// Generated Nov 14, 2014 9:01:22 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Seat generated by hbm2java
 */
@Entity
@Table(name="Seat"
    ,schema="dbo"
    ,catalog="Alpha"
)
public class Seat  implements java.io.Serializable {


     private ShowtimeId id;
     private String seat;
     private Integer type;

    public Seat() {
    }

	
    public Seat(ShowtimeId id, String seat) {
        this.id = id;
        this.seat = seat;
    }
    public Seat(ShowtimeId id, String seat, Integer type) {
       this.id = id;
       this.seat = seat;
       this.type = type;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="time", column=@Column(name="time", nullable=false, length=5) ), 
        @AttributeOverride(name="cinema", column=@Column(name="cinema", nullable=false) ) } )
    public ShowtimeId getId() {
        return this.id;
    }
    
    public void setId(ShowtimeId id) {
        this.id = id;
    }

    
    @Column(name="seat", nullable=false, length=3)
    public String getSeat() {
        return this.seat;
    }
    
    public void setSeat(String seat) {
        this.seat = seat;
    }

    
    @Column(name="type")
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }




}


