package model.pojo;
// Generated Nov 12, 2014 10:39:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShowtimeId generated by hbm2java
 */
@Embeddable
public class ShowtimeId  implements java.io.Serializable {


     private String time;
     private int cinema;

    public ShowtimeId() {
    }

    public ShowtimeId(String time, int cinema) {
       this.time = time;
       this.cinema = cinema;
    }
   


    @Column(name="time", nullable=false, length=5)
    public String getTime() {
        return this.time;
    }
    
    public void setTime(String time) {
        this.time = time;
    }


    @Column(name="cinema", nullable=false)
    public int getCinema() {
        return this.cinema;
    }
    
    public void setCinema(int cinema) {
        this.cinema = cinema;
    }




}


