package model.pojo;
// Generated Nov 14, 2014 9:01:22 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ShowtimeId generated by hbm2java
 */
@Embeddable
public class ShowtimeId implements java.io.Serializable {

    private String time;
    private int cinema;

    public ShowtimeId() {
    }

    public ShowtimeId(String time, int cinema) {
        this.time = time;
        this.cinema = cinema;
    }

    @Column(name = "time", nullable = false, length = 5)
    public String getTime() {
        return this.time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    @Column(name = "cinema", nullable = false)
    public int getCinema() {
        return this.cinema;
    }

    public void setCinema(int cinema) {
        this.cinema = cinema;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof ShowtimeId)) {
            return false;
        }
        ShowtimeId castOther = (ShowtimeId) other;

        return ((this.getTime() == castOther.getTime()) || (this.getTime() != null && castOther.getTime() != null && this.getTime().equals(castOther.getTime())))
                && (this.getCinema() == castOther.getCinema());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getTime() == null ? 0 : this.getTime().hashCode());
        result = 37 * result + this.getCinema();
        return result;
    }

}
