package model.pojo;
// Generated Nov 12, 2014 10:39:01 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Showtime generated by hbm2java
 */
@Entity
@Table(name="Showtime"
    ,schema="dbo"
    ,catalog="Alpha"
)
public class Showtime  implements java.io.Serializable {


     private ShowtimeId id;
     private String mname;

    public Showtime() {
    }

    public Showtime(ShowtimeId id, String mname) {
       this.id = id;
       this.mname = mname;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="time", column=@Column(name="time", nullable=false, length=5) ), 
        @AttributeOverride(name="cinema", column=@Column(name="cinema", nullable=false) ) } )
    public ShowtimeId getId() {
        return this.id;
    }
    
    public void setId(ShowtimeId id) {
        this.id = id;
    }

    
    @Column(name="mname", nullable=false, length=50)
    public String getMname() {
        return this.mname;
    }
    
    public void setMname(String mname) {
        this.mname = mname;
    }




}


