package model.dao;
// Generated Nov 12, 2014 10:39:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name="test"
    ,schema="dbo"
    ,catalog="Alpha"
)
public class Test  implements java.io.Serializable {


     private int id;
     private String session;

    public Test() {
    }

	
    public Test(int id) {
        this.id = id;
    }
    public Test(int id, String session) {
       this.id = id;
       this.session = session;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="session", length=50)
    public String getSession() {
        return this.session;
    }
    
    public void setSession(String session) {
        this.session = session;
    }




}


